[tools]
hk = "latest"
pkl = "latest"
gitleaks = "latest"
actionlint = "1.7.12"
zizmor = "1.26.1"
zig = "0.16.0"
"npm:oxlint" = "latest"
"npm:oxfmt" = "latest"

[env]
HK_MISE = 1

[hooks]
postinstall = "hk install --mise"
